pipeline {
    agent any
    tools {
        maven 'maven3' // Use the version that satisfies the plugin requirement
    }
    stages {
        stage('checkout') {
            steps {
                git 'https://github.com/AlavalapatiRupeshReddy/simple-java-maven-app.git'
            }
        }  
    }
}
