pipeline {
    agent any
    tools {
        maven 'maven3' // Use the version that satisfies the plugin requirement
    }
    stages {
        stage('checkout') {
            steps {
                git 'https://github.com/AlavalapatiRupeshReddy/simple-java-maven-app.git'
            }
        }
            stage('Compile & build')
            {
            steps
                {
                   sh "${env.MAVEN_HOME}/bin/mvn clean package" 
                }             
        }
        stage('Build Docker Image') {
    steps {
        script {
            def dockerImage = docker.build("simple_image:${env.BUILD_ID}")
            dockerImage.push()
        }
    }
}

    }
}
